version: "3"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 1486:1486
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  web:
    container_name: fastapi_app
    build: .
    command: sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      # mounting volume assures host machine and container are in sync
      - .:/app
    depends_on:
      - db
    restart: always
