name: fastapi-dash-training

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - attrs>=17.3.0
  - black
  - fastapi=0.92.0
  - flake8=6.0.0
  - dash=2.8.1
  - dash-bootstrap-components=1.3.1
  - ipywidgets
  - isort
  - pandas=1.5.3
  - pip
  - pyarrow=11.0.0
  - pyyaml=6.0
  - requests=2.28.2
  - uvicorn=0.20.0
  - webargs<6.0
  - pip:
    - Werkzeug==2.2.3
    - pyarrow==11.0.0