\c fastapi_db;

CREATE TABLE IF NOT EXISTS users (
    ID serial PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,

    UNIQUE (FIRST_NAME, LAST_NAME, email)
);

CREATE TABLE IF NOT EXISTS stores (
    ID serial PRIMARY KEY,
    STORE_NAME VARCHAR(50) NOT NULL,

    UNIQUE(STORE_NAME)
);

CREATE TABLE IF NOT EXISTS products (
    ID serial PRIMARY KEY,
    STORE_ID integer REFERENCES stores (ID) NOT NULL,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    STOCK_LEVEL integer NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
